project:
  type: book
  output-dir: docs

book:
  title: "Art catalogue test"
  author: "Simon Worthington"
  date: "2023-03-01"
  chapters:
    - index.qmd
    - colophon.ipynb
  repo-url: https://github.com/SimonXIX/art_catalogue_test
  repo-actions: [edit]
  downloads: [pdf]

comments:
  hypothesis: true

#bibliography: references.bib

format:
  html:
    theme: minty
    number-sections: false
  pdf:
    documentclass: scrreprt
